### ISSUE TITLE
compilation error gfortran 5.1.0

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#144]
I have tried to compile `piernik` with gfortran 5.1.0 and hdf5 1.8.15 and get this error message.

```
mpif90  -fdefault-real-8 -ffree-form -std=gnu -fimplicit-none -ffree-line-length-none -g -O2 -fstack-arrays -c gravity.F90
common_hdf5.F90:950:64:

       use hdf5,     only: HID_T, H5P_FILE_ACCESS_F, h5pcreate_f, h5pset_fapl_m
                                                                1
Error: Symbol ‘h5pset_fapl_mpio_f’ referenced at (1) not found in module ‘hdf5’
common_hdf5.F90:951:49:

          &                H5FD_MPIO_COLLECTIVE_F, h5pset_dxpl_mpio_f, H5P_DATA
                                                 1
Error: Symbol ‘h5pset_dxpl_mpio_f’ referenced at (1) not found in module ‘hdf5’
Makefile:149: recipe for target 'common_hdf5.o' failed
make: *** [common_hdf5.o] Error 1
```

**Comment by migueldvb** [comment]
Sorry, I did not use the `–enable-parallel` option to build HDF5. It looks like the code compiles correctly with gfortran 5.1.0.
